language: cpp

compiler:
    - clang
    - gcc

install:
    - make -f dependencies.mak install-travis

before_script:
    - if [[ $CXX == "g++" ]]; then
      export CXX="g++-4.8";
      fi

script:
    - make -f travis.mak build test install
